[package]
name = "mujoco"
version = "0.1.0"

[[app]]
name = "Car"
main = "src/Car.lf"
target = "C"
platform = "Native"

[app.properties]

[dependencies]
mujoco-c = {version=">=0.1", git="https://github.com/lf-lang/mujoco-c.git", branch="main"}
